opt_in_rules: # some rules are only opt-in
  - atributes
  - closure_spacing
  - explicit_init
  - first_where
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalesing
  - sorted_imports

disabled_rules: # rule identifiers to exclude from running
  - cyclomatic_complexity
  - todo
  - variable_name
  - type_name
  - line_length
  - file_length
  - function_body_length
  - type_body_length
  - unused_setter_value
  - legacy_nsgeometry_functions
  - force_cast

switch_case_alignment:
  indented_cases: true
trailing_comma:
  mandatory_comma: true
line_length:
  warning: 120
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - .build
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)
custom_rules:
  no_ui_color_initializers:
    excluded: ".*Color.*swift"
    name: "Don't use color initializers"
    regex: '(\s+)(UIColor\(|UIColor\.|Color\()'
    message: "Only use the colors from the Design System"
    severity: error
